### ISSUE TITLE
Running Gaia Sky in Oculus Rift

### ISSUE THREAD

**Issue by wna-se** [langurmonkey/gaiasky#136]
I found that Gaia Sky should be able to run in Oculus Rift but I didn't manage to get any signal to the headset by pressing left_ctrl+s.  Are there any prerequisites to activate the stereoscopic mode in Oculus? 

I found the instructions at: http://gaia-sky.readthedocs.io/en/latest/Stereoscopic-mode.html

**Comment by langurmonkey** [comment]
Head tracking integration is not yet finished, when the backend is ready I will integrate it with OpenVR which I understand is supported by the Oculus Rift.
I will modify the documentation in the mean time to make this clearer.
