### ISSUE TITLE
Cinematic camera setting not saved

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#144]
On the current master, 292d1d84a0b3b98df7c234249a9cf928a3fc9a72, the GUI setting "Cinematic camera" is not saved as preference, unless the other settings. Is that on purpose or by mistake?

**Comment by langurmonkey** [comment]
I tried 292d1d8 and also the current [master](/langurmonkey/gaiasky/tree/master) (59f9cd8) and it works for me. What are the exact steps that lead to the issue? I do:

1. Open Gaia Sky
2. Tick or untick cinematic camera checkbox
3. Close Gaia Sky
4. Open Gaia Sky

And the setting is saved and restored correctly.

**Comment by vga101** [comment]
Hmm, sorry for that. I also can't reproduce it anymore. Must have been due to my messy testing... :-(
