### ISSUE TITLE
Milky Way texture off when rotated

### ISSUE THREAD

**Issue by mgreter** [langurmonkey/gaiasky#158]
Rotating the Milky Way gives different results for front and back side (Gaia Sky 1.0.4).

![gaiasky-earth-mw-side-a](https://user-images.githubusercontent.com/282293/27668304-a3139912-5c80-11e7-8b94-cc5ca9fc830c.png)
![gaiasky-earth-mw-side-b](https://user-images.githubusercontent.com/282293/27668305-a314cc88-5c80-11e7-864b-b2856a621ad1.png)

Reference: https://en.wikipedia.org/wiki/Galactic_quadrant#/media/File:Galactic_longitude.JPG

**Comment by langurmonkey** [comment]
Thanks for spotting that! It has been fixed in the master. BTW, your WebGL solar system/milky way explorer is amazing, I love it!
