### ISSUE TITLE
Test script "getobject-test.py" crashes

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#172]
Calling provided `android/assets/scripts/tests/getobject-test.py` test script crashes when called in scripting GUI. Console output below.
```
Traceback (most recent call last):
  File "<script>", line 18, in <module>tests/goto-capture-test.py'
        at gaia.cu9.ari.gaiaorbit.script.EventScriptingInterface.goToObject(EventScriptingInterface.java:585)
        at gaia.cu9.ari.gaiaorbit.script.EventScriptingInterface.goToObject(EventScriptingInterface.java:550)
        at gaia.cu9.ari.gaiaorbit.script.EventScriptingInterface.goToObject(EventScriptingInterface.java:541)
        at gaia.cu9.ari.gaiaorbit.script.EventScriptingInterface.goToObject(EventScriptingInterface.java:536)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

java.lang.NullPointerException: java.lang.NullPointerException

```

(Tested with 8e5c7c1b35614d71e7ae3df1734275e285d58928 since most recent master commit crashes for me).

Cheers,
Volker

**Comment by langurmonkey** [comment]
It works for me using the current octree multifile catalog. I submitted a fix (942ab2838a593c47bf6cc93c84b562dabe198e62) which crashed the master; otherwise I can't reproduce this. Can you test again and see if the master work?
There have been several major changes, so the whole thing is a bit unstable now, but I hope it will converge very fast. The legacy catalog to use in the master is:
```
android/assets/data/catalog-tgas-hyg-lod-old.json
```
Use this as your catalog file in the properties file, key `data.json.catalog`

**Comment by vga101** [comment]
Sorry, doesn't fix it for me with master. Some data structures seem to mismatch: 
```
...
:desktop:run
Display mode set to 1280x720, fullscreen: false
12:00:19: GaiaSky - GLSL-Version: 4.50 NVIDIA
12:00:20: OctreeMultiFileLoader - Lade data/octree/tgas/metadata.bin
12:00:20: Fehlermeldung: com.badlogic.gdx.utils.GdxRuntimeException: File not found: data/octree/tgas/metadata.bin (Internal)
12:00:20: Initialisierung des Renderers und der Benutzeroberfläche (GUI)
```
File `data/octree/tgas/metadata.bin` is given in the legacy catalog you mention, but I don't have the corresponding file (it is in none of the download archives on the github main page, for versions 1.0.3, 1.0.4 and 1.5.0).

**Comment by langurmonkey** [comment]
The files are the same, just move them from `data/octree` to `data/octree/tgas` and it should work (download archive `1.5.0`).

**Comment by vga101** [comment]
Ok, I have it working now after doing the following:
1. extract `20170427_tgas_gaiasky_1.5.0.tar.gz` in directory `android/assets/data/octree`
2. rename or symlink `tgas_multifile` to `tgas`
Note that `20170427_tgas_gaiasky_1.5.0.tar.gz` is not listed as downloads on the github start page anymore, but I still have it locally. The currently listed 1.5.0 archive file `20170713_tgas_gaiasky_1.5.0.tar.gz` has a different content.

I guess this is because of the major changes you're working on and will be gone later, so don't worry - I'm fine here.

Anyway, now `getobject-test.py` works for me, too. Thanks. :-)

**Comment by langurmonkey** [comment]
Hmmm yes, sorry, I've been changing lots of stuff here, and most probably even the online archive file (20170713) is outdated. I'm not even sure what's in there anymore... The new method is mostly GPU-based and can display many more stars at once with far higher FPS.
