### ISSUE TITLE
Docs don't mention where record data appears

### ISSUE THREAD

**Issue by hakphar** [langurmonkey/gaiasky#198]
There used to be a Gaia Sky data folder in the main, but now it's gone and I don't know where anything went.

**Comment by langurmonkey** [comment]
I'm not sure I follow. The data folder is, as always, under `android/assets/data` ([see here](https://github.com/langurmonkey/gaiasky/tree/master/android/assets/data)). What is not in the git repository anymore are the increasingly large and complex catalog files. The instructions to get the data are posted in the official docs [here](http://gaia-sky.readthedocs.io/en/latest/Running-gaia-sky.html#getting-the-catalog-data).

**Comment by hakphar** [comment]
Spelling error in pakagin Gaia sky,  'Packaging Gaia Sky'.

And thank you for pointing me to the right folder. Last time I saw this, it didn't even have an android folder.

**Comment by langurmonkey** [comment]
Fixed, thanks!
