### ISSUE TITLE
On Windows, install fails with "Could not determine java version from '9.0.1'

### ISSUE THREAD

**Issue by kevinjardine** [langurmonkey/gaiasky#204]
I am running JDK 9.0.1

**Comment by kevinjardine** [comment]
I am running JDK 9.0.1

**Comment by kevinjardine** [comment]
OK, I solved this by installing gradle 4.2.1 locally and following the gradle instructions to create new wrapper files for 4.2.1. Presumably the git install should also include these updated wrapper files.

**Comment by langurmonkey** [comment]
Yes, I think gradle included java 9 suport in version 4.2.1. I myself have not tried java 9 with Gaia Sky yet, so it is good to know that it works ;)
Will update the gradle wrapper version asap.
