### ISSUE TITLE
Preferences window shows wrong version number

### ISSUE THREAD

**Issue by vga101** [langurmonkey/gaiasky#234]
The title bar of the preferences window shows an incorrect (old) version number of Gaia Sky:
![grafik](https://user-images.githubusercontent.com/17450735/34166991-bbb3cb16-e4e0-11e7-83d9-b203eb302a4f.png)

**Comment by langurmonkey** [comment]
Is that in the development version (running with gradle/IDE)? If so, that is correct, as ``1.0.3`` is hardcoded in the file ``assets/data/dummyversion``, which is used when running from code. Otherwise, a version file is generated every time the application is packed.

**Comment by vga101** [comment]
Yes, it's in the development version with gradle. Was just surprised, but all ok then.
