### ISSUE TITLE
Is this update also coming?

### ISSUE THREAD

**Issue by RED29** [langurmonkey/gaiasky#261]
On 25 April there will be a major data release. Is this also planned for the software?

https://twitter.com/esascience/status/981887720183291905?s=21

**Comment by langurmonkey** [comment]
Yes, we will publish [version 2.0 of Gaia Sky on 25 April](../milestone/5). The default will come with the stars of GDR2 with a 2% parallax relative error or less (a few million) and we'll offer larger catalogs (12.5%, 50%, etc.) as an optional download.
