### ISSUE TITLE
Maximum time reached

### ISSUE THREAD

**Issue by RED29** [langurmonkey/gaiasky#271]
Is it possible to extend or disable the maximum time limit? If you forward in time, it will reach a maximum point.

**Comment by langurmonkey** [comment]
It is not possible right now, the max and min times are hardcoded to +5 Myr and -5 Myr, and this is already a stretch. The linear velocity approximation of proper motions just does not make sense with such long times; orbits should be integrated around the galaxy assuming a galactic potential model.

**Comment by RED29** [comment]
I completely understand why it makes sense that there is a limit. I was using for a instruction to show the motion of the galaxy in terms of x years. If you move speed forward in time, our galaxy is not a static view but a place full of motion. Maybe I can make a video for that.
