### ISSUE TITLE
Request please...Type Visibility: Constellations, toggle selection

### ISSUE THREAD

**Issue by nathanialbb** [langurmonkey/gaiasky#275]
Hi All :)

Seriously awesome program.
Type Visibility: Constellations. When viewed from other star locations, all constellation lines drawn (results in confusing mess), but ability to draw only constellation lines associated with selected star, would help enormously.
GUI combo list of Constellations, with ability to select individual constellation, perhaps?

Thank you :)))

**Comment by langurmonkey** [comment]
Implemented in all branches, will be available in next release or right now if you run from source
