### ISSUE TITLE
Catalogs download 2.0.3.41 on macOS

### ISSUE THREAD

**Issue by RED29** [langurmonkey/gaiasky#304]
**Describe the bug**
After starting the Gaia Sky app on the macOS you get a question to download a catalog.
You get a popup with a button "download"  in the directory "Users/...../.gaiaksy/catalogs/..."

After hitting the button, nothing happens. 
Looking in the directory "Users/...../.gaiaksy/catalogs/..." you see a temp.tar.gz ?

**To Reproduce**
1. Start gaiasky (first time)
2. You get a popup, hitting download button
3. nothing happens, the download button is now showing "done"

**Expected behavior**
1. Download a certain catalog
2. Starting Gaia Sky

**Screenshots**

**Desktop (please complete the following information):**
- macOS High Sierra
- Gaia Sky 2.0.3.41

**Comment by langurmonkey** [comment]
Thanks for reporting. We've not seen this behaviour in our tests with macOS yet.
I need a log file, here's how to get it: 

1. Delete the ~/.gaiasky/catalogs/temp.tar.gz
2. Launch Gaia Sky again, and try to download the catalog
3. Once the app has initialized, click on the log icon (at the bottom right of the controls window) and export the log to a file.
4. Attach log file here.

Thanks!

**Comment by RED29** [comment]
Strange..

1. I deleted ~/.gaiasky/catalogs/temp.tar.gz
2. I start the Gaia Sky again
3. You see the pop-up, you hit download, and the button with "start" will than greyout. So the Gaia Sky can't start. It forced me to quit Gaia Sky. See attachment.
4. I start Gaia Sky again, and hit "start"
5. See the included 
[2018-09-04T21:31:07.289Z_gaiasky.log](https://github.com/langurmonkey/gaiasky/files/2350327/2018-09-04T21.31.07.289Z_gaiasky.log)
![screenshot](https://user-images.githubusercontent.com/11861774/45059253-a9ccf080-b09b-11e8-99c1-db85af408731.png)

log file

**Comment by langurmonkey** [comment]
Usually, the first time you click "Download now", the progress should be shown in the button itself (see [here](https://twitter.com/GaiaSky_Dev/status/1034433831267434496). Looking at your log, it seems that the catalog download failed but otherwise Gaia Sky starts just fine.
Are you getting the "Catalog download" dialog at startup?

1. If so, try downloading again. Otherwise see point two.
2. Otherwise, you can still download the catalog(s) manually [here](https://zah.uni-heidelberg.de/institutes/ari/gaia/outreach/gaiasky/downloads/#dr2catalogs).

On an unrelated note, a new update is coming very soon with a proper download manager system not only for the catalogs, but for all data. That should hopefully fix most problems with the current downloader.

**Comment by RED29** [comment]
Ok, the download popup start at beginning of Gaia Sky. If hit download, nothing happens, only the same temp file is showing up. Also I dont see any download progress bar..

Nice to see the update! Is the update, you referring in the today pre-Christmas release?

**Comment by langurmonkey** [comment]
> Ok, the download popup start at beginning of Gaia Sky. If hit download, nothing happens, only the same temp file is showing up. Also I dont see any download progress bar..

Do you have an internet connection in the computer where you are trying this?

> Nice to see the update! Is the update, you referring in the today pre-Christmas release?

Yes, I'll release in the follwoing days or weeks.

**Comment by nornagon** [comment]
I'm also seeing this issue. Interestingly, the temp.tar.gz is actually an HTML file, with this contents:

```
$ cat ~/.gaiasky/catalogs/temp.tar.gz
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /gaiasky/files/catalogs/dr2/dr2-20-0.5.tar.gz was not found on this server.</p>
</body></html>
```

**Comment by RED29** [comment]
Yes there is internet. 
Can’t wait to see the update. Thanks

**Comment by langurmonkey** [comment]
Would you be willing to test version 2.1.0 before release? I can make the macOS build available to you two. I'd like to make sure it works.

**Comment by RED29** [comment]
Yes, I would like to test the new version (2.1)

Version 2.03: I can’t test it right now, I will test it later this day. 

Thanks

**Comment by langurmonkey** [comment]
Here it is, [gaiasky_macos_2_1_0_d30419fb.dmg](http://gaia.ari.uni-heidelberg.de/gaiasky/files/releases/prerelease-2.1.0/gaiasky_macos_2_1_0_d30419fb.dmg). Let me know your thoughts and if everything works as expected.

**Comment by RED29** [comment]
I have tested for a while:

1. The download manager at startup works great. Nice download and unpacking.
1A. Suggestion: it would be nice if there a selection for which database you want, the small, medium or large one.

2. In the control panel the date & timestamp is not clear visible. Maybe it was before the same. See attachment.

3. Please add PS4 controller label in, because it works. Settings > Controls

4. I find the spacecraft mode little bit difficult to handle. It's spinning, and the screen turns complete black. I hope there will some kind of simple trick to stabilize the spacecraft. See are similar project, like space engine that had the same problems. 
4A. Camera bug: If you first select **Gaia FoV1** and than back to **Spacecraft** the Gaia Sky will fatally crash. 

5. The Gaia Sky is still showing 2.03 instead of 2.1, in the installer as in the Gaia Sky it self.

I will test tomorrow a bit deeper.

![cosmetic-controlpanel time_data](https://user-images.githubusercontent.com/11861774/45184006-f2b0b080-b225-11e8-8af0-0ce0d320ebcb.png)

**Comment by langurmonkey** [comment]
Thanks for the feedback! Some answers:

> The download manager at startup works great. Nice download and unpacking.
> 1A. Suggestion: it would be nice if there a selection for which database you want, the small, medium or large one.

You can download any of them by selecting the checkboxes. To select which catalog is actually loaded, there is an option in the Preferences window, Data tab, where you can enable the dataset selection at startup.

> In the control panel the date & timestamp is not clear visible. Maybe it was before the same. See attachment.

I'll see if I have any other more readable monospace font available.

> I find the spacecraft mode little bit difficult to handle. It's spinning, and the screen turns complete black. I hope there will some kind of simple trick to stabilize the spacecraft. See are similar project, like space engine that had the same problems.

There are actually controls for stabilizing and stopping the spacecraft (first and second buttons below the attitude indicator). You can also set a 'friction' force to make the spacecraft easier to handle. Will add some words on this to the docs.

> The Gaia Sky is still showing 2.03 instead of 2.1, in the installer as in the Gaia Sky it self.

It won't show 2.1.0 until the official release.

**Comment by langurmonkey** [comment]
See [here](https://gaia-sky.readthedocs.io/en/latest/Camera-modes.html#spacecraft-mode) for more info on the spacecraft mode controls.

**Comment by RED29** [comment]
> You can download any of them by selecting the checkboxes. 
Which checkboxes are you referring to? The download manager "catalog download" at the beginning of a fresh install of Gaia Sky only gives you the option to download the default dataset. Ofcourse you can always add it manually. 

> To select which catalog is actually loaded, there is an option in the Preferences window, Data tab, where you can enable the dataset selection at startup.
This is very nice thing! Great. 

> There are actually controls for stabilizing and stopping the spacecraft (first and second buttons below the attitude indicator). You can also set a 'friction' force to make the spacecraft easier to handle. Will add some words on this to the docs.
Great, I have seen the update.

> 4A. Camera bug: If you first select Gaia FoV1 and than back to Spacecraft the Gaia Sky will fatally crash.
This is a bug, I hope you have seen it. Otherwise, its not a very annoying thing. There is a workaround.

Thanks a lot.

**Comment by langurmonkey** [comment]
> Which checkboxes are you referring to? The download manager "catalog download" at the beginning of a fresh install of Gaia Sky only gives you the option to download the default dataset.

Sorry, I thought you were talking about version `2.1.0`.

> This is a bug, I hope you have seen it. Otherwise, its not a very annoying thing. There is a workaround.

Will fix ;)

**Comment by langurmonkey** [comment]
Is this still relevant with `2.1.2`?

**Comment by langurmonkey** [comment]
What does it do exactly? I just tried and it seems to work. This catalog is located [here](http://gaia.ari.uni-heidelberg.de/gaiasky/files/autodownload/catalog-dr2-large.tar.gz), can you access it with your browser?

**Comment by RED29** [comment]
Ok, I have just tried it again. The download succeed nice and easy. The error is in the unzipping/unpacking. Can't figure why. My storage is not full. From the browser the download succeed and also the unpacking. 

So in **.gaiasky/data/**

there is the **temp.tar.gz** but it seems that it can't unpack it...it stays there.

In **.gaiasky/data/catalog/**

there is dr2-large ?? and it is big enough to assume that this is the package..

After starting, the Gaia Sky hangs on SGLoader - Initalizing renderer and Gui.
![unpack-failed](https://user-images.githubusercontent.com/11861774/46042011-9221de80-c114-11e8-9ec5-8a08d18045dd.png)
![freeze](https://user-images.githubusercontent.com/11861774/46042012-94843880-c114-11e8-8323-cd6376113880.png)

**Comment by langurmonkey** [comment]
Can you attach the output.log and error.log in `/Applications/Gaia\ Sky.app/Content/Resources/app`?

**Comment by RED29** [comment]
Hi, excuse for the delay response. Here is a screenshot and .log found in  /Applications/Gaia\ Sky.app/Content/Resources/app

![screenshot](https://user-images.githubusercontent.com/11861774/47006079-6901d600-d135-11e8-9953-f141eeb91846.png)
[error.log](https://github.com/langurmonkey/gaiasky/files/2482309/error.log)

**Comment by langurmonkey** [comment]
Is [error.log](https://github.com/langurmonkey/gaiasky/files/2482309/error.log) a binary file? It contains nonsense if opened with a text editor.
