### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by kochmich** [langurmonkey/gaiasky#315]
I have got win 10, 32 GB Ram, gtx 1070ti. I can start and see the download screen. After this, the window is just closing. It is showing the extracting procedures and the closing.
Restarting does the same. Just closing.
I tried 64 bit and 32 bit.
I also deleted the settings and also the .gaiasky folder many times.
What can it be?
Greetings and thanx for your great work!

**Comment by langurmonkey** [comment]
Thanks for the report! Could you attach the `error.log` and `output.log` files located in your Gaia Sky installation directory?

**Comment by Niuskir** [comment]
I have the same problem with a GTX 1070 12 GB RAM & Win 10:
output.log:
Microsoft Windows [Version 10.0.17763.134]
C:\Program Files\Gaia Sky>gaiasky.cmd

C:\Program Files\Gaia Sky>.\jre\bin\java -Xms2g -Xmx4g -XX:+UseG1GC -Dassets.location=.\ -cp "lib\*" gaia.cu9.ari.gaiaorbit.desktop.GaiaSkyDesktop
Nov 17, 2018 10:09:05 PM: GaiaSky - 2.1.3 - build 874bf4ff
Nov 17, 2018 10:09:13 PM: GaiaSky - Display mode - 1280x720 - Fullscreen: false
Nov 17, 2018 10:09:13 PM: GaiaSky - Device - GeForce GTX 1070/PCIe/SSE2
Nov 17, 2018 10:09:13 PM: GaiaSky - GLSL version - 4.60 NVIDIA
Nov 17, 2018 10:09:13 PM: GaiaSky - Java version - 1.8.0_181 - Oracle Corporation
Nov 17, 2018 10:09:13 PM: NaturalControllerListener - Controller mappings file set to mappings/xbox360.win.controller
Nov 17, 2018 10:09:14 PM: DownloadHelper - Downloading: http://gaia.ari.uni-heidelberg.de/gaiasky/files/autodownload/gaiasky-data.json
Nov 17, 2018 10:09:14 PM: DownloadHelper - Download finished: C:/Users/Niek en Patricia/.gaiasky/tmp/gaiasky-data.json
Nov 17, 2018 10:09:17 PM: StreamingOctreeLoader - OctreeGroupLoader - Maximum loaded stars setting: 5500000
Nov 17, 2018 10:09:17 PM: OctreeGroupLoader - Loading data/catalog/dr2-verysmall/metadata.bin
Nov 17, 2018 10:09:17 PM: Error: GaiaSky - com.badlogic.gdx.utils.GdxRuntimeException: com.badlogic.gdx.utils.GdxRuntimeException: Couldn't load dependencies of asset: C:/Users/Niek en Patricia/.gaiasky/data/catalog-dr2-verysmall.json,data/data-main.json
Nov 17, 2018 10:09:17 PM: GaiaSky - Configuration saved to C:\Users\Niek en Patricia\.gaiasky\global.properties

**Comment by langurmonkey** [comment]
Thanks! I'm suspecting it has something to do with the spaces in the path, which may not be handled correctly in the windows version. I will try to replicate it.

**Comment by langurmonkey** [comment]
I have found and patched the error. Basically, that version was wrongly compiled with Java 11, which pointed to some conflicting methods in `ShortBuffer` and `MappedByteBuffer` when running with Java 8 (which is bundled with the application in the Windows and macOS releases).
I have updated the release files [here](https://zah.uni-heidelberg.de/institutes/ari/gaia/outreach/gaiasky/downloads/), but you can also just download the [gaiasky-core.jar](http://gaia.ari.uni-heidelberg.de/gaiasky/files/temp/874bf4ff/gaiasky-core.jar) file and copy it in your `[gaiasky_install_folder]/lib` folder if you do not want to download the whole thing again. This should fix it.

**Comment by kochmich** [comment]
Thank you - that fixed it! 😊



Michael


______________________________________________
Feuer und Flamme für die Kelten im Hochwald!
<https://www.eao-otzenhausen.de/veranstaltung/detail/archaeologentage-2017/>

Freundeskreis keltischer Ringwall Otzenhausen e.V.
Verein zur Förderung der Archäologie im Hochwald
Fon: +49 (0)151 503 762 35
www.hochwaldkelten.de

Vereinssitz:
Trierer Straße 5 | 66620 Nonnweiler
Rg.Nr. 1223 Registergericht St. Wendel
Vorsitzender: Michael Koch

_____________________________________

Michael Koch
Projektleitung Archäologie in der Großregion
Projektentwicklung Keltenpark Otzenhausen
Europäische Akademie Otzenhausen gGmbH
Europahausstraße 35
66620 Nonnweiler
Deutschland
Fon: +49 (0)6873 662-267
Fax: +49 (0)6873 662-350<mailto:koch@eao-otzenhausen.de><http://www.eao-otzenhausen.de/>
koch@eao-otzenhausen.de<mailto:koch@eao-otzenhausen.de>
www.eao-otzenhausen.de<http://www.eao-otzenhausen.de/>



________________________________
Von: Toni Sagristà Sellés <notifications@github.com>
Gesendet: Dienstag, 20. November 2018 11:19
An: langurmonkey/gaiasky
Cc: kochmich; Author
Betreff: Re: [langurmonkey/gaiasky] Won't start (#315)


I have found and patched the error. Basically, that version was wrongly compiled with Java 11, which pointed to some conflicting methods in ShortBuffer and MappedByteBuffer when running with Java 8 (which is bundled with the application in the Windows and macOS releases).
I have updated the release files here<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fzah.uni-heidelberg.de%2Finstitutes%2Fari%2Fgaia%2Foutreach%2Fgaiasky%2Fdownloads%2F&data=02%7C01%7C%7C4403477246594c70b7d908d64ed1b253%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636783059870112026&sdata=4hMSkEhM02KOPfUAY8woXeTlQIN7J1wYtGJqPJpjxg0%3D&reserved=0>, but you can also just download the gaiasky-core.jar<https://eur04.safelinks.protection.outlook.com/?url=http%3A%2F%2Fgaia.ari.uni-heidelberg.de%2Fgaiasky%2Ffiles%2Ftemp%2F874bf4ff%2Fgaiasky-core.jar&data=02%7C01%7C%7C4403477246594c70b7d908d64ed1b253%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636783059870112026&sdata=zcYfyK9exH4%2BcxzNei1L2S4JYtp6Qj%2Bpqmzc67DxHYs%3D&reserved=0> file and copy it in your [gaiasky_install_folder]/lib folder if you do not want to download the whole thing again. This should fix it.

**Comment by Niuskir** [comment]
Fixed it for me as well. Thx!!!

Niek
