### ISSUE TITLE
Not truly compatible with Oculus Rift

### ISSUE THREAD

**Issue by jhoar** [langurmonkey/gaiasky#44]
The current implementation is not really compatible with Oculus Rift. It does work in VR mode, but there's a few things to do to make to a really immersive experience.

You are not applying the correct distortion or chromatic effects which make the HMD and lens combination compatible with the human visual system so it looks quite bad away from the centre of the FOV.

There is also no head-tracking, which makes it a little nauseating after a while.

You might want to automatically disable the UI when in VR mode as they are pretty useless with the Oculus RIft, it simply does not have the resolution to support such small text and having them in the edges and corners makes it impossible to read anyway, not to mention quite immersion breaking.

Brad Smith has a java binding to the Oculus Rift libraries:

https://github.com/jherico/jovr

which does not make these problems impossible to solve!
Which should enough to implement

**Comment by langurmonkey** [comment]
Yes, I suspected it does not work well with the OR, for I have never tested it. About the head tracking, it is implemented and working well for android (Google Cardobard or similar), but the android version is not released yet.
Thanks for the link, I will take a look, but I fear I wont be implementing a proper OR version until I can grab one of these myself ;)

**Comment by langurmonkey** [comment]
Lens distortion has been added (see #64). Also, the post processing effects are fixed and the interface disappears in VR mode (see 018a7868556367a6845a54ec7739d3441d154d25).

**Comment by langurmonkey** [comment]
There is now a [vr](/langurmonkey/gaiasky/tree/vr) branch with an already usable version integrated with OpenVR (SteamVR, supporting HTC Vive and Oculus Rift). For more info, see the [README.md](/langurmonkey/gaiasky/blob/vr/README.md) file in the branch.
